all:
	pandoc --from=markdown --to=html5 --template=template.html --standalone --section-divs --variable theme=beige --variable transition="linear" --parse-raw --highlight-style kate 201503-monadbase.md -o 201513-monadbase.html

